### ISSUE TITLE
Not able to run environment.yml 

### ISSUE THREAD

**Issue by Chaitanya887** [matanr/capex#2]
![image](https://github.com/matanr/capex/assets/99232731/e9f456b4-d7af-462c-869a-ad1e9a30344b)
Showing like this when ran the commands

**Comment by matanr** [comment]
Hi @Chaitanya887,
Unfortunately the repository was not tested on Windows, but only on Linux.
Please try to manually install the required packages. Alternatively try to provide alternative channels.

**Comment by Chaitanya887** [comment]
Thanks for your reply (sorry for being late to reply back)
So what you are saying is to install all the dependencies and all the packages under pip right ?
![image](https://github.com/matanr/capex/assets/99232731/29fc3a5d-8f68-4436-ad62-d69d765af00b)
![image](https://github.com/matanr/capex/assets/99232731/0a51d11e-ff08-4a32-a25f-fc24b2f8a139)

**Comment by Chaitanya887** [comment]
At the same time I also wanna ask have you provided the link of the pretrained model in the repo or not ?

**Comment by matanr** [comment]
Yes, I would try to install these packages.
But I think it is not important from where you install each package (pip or not).

Yes the pretrained model can be download from [here](https://drive.google.com/file/d/1hmvxTjP84YywVhhckMt1NHc3wUTqQIqp).

**Comment by Chaitanya887** [comment]
```
docker run --name capex -v {DATA_DIR}:/workspace/CapeX/CapeX/data/mp100 -it matanru/capex /bin/bash
```
can you specify what what should we put in DATA_DIR field?
Also what is this address specifying  : /workspace/CapeX/CapeX/data/mp100

**Comment by Chaitanya887** [comment]
Can u update the installation part cuz it seems like when we go with environment creation and demo file there's a bunch of errors that keep on coming which is mostly related to mmcv and if we go with docker image it say its been scheduled to be deleted and can't be used :/

**Comment by matanr** [comment]
@Chaitanya887,
Are you still trying to set-up the environment in Windows?
As I mentioned, this repository was tested only on Linux.
If you still want to try and set-up the environment in Windows, please follow mmcv / mmpose instructions.

Since you didn't provide any specific errors/logs, I assume the deprecation notification you see in the docker image relates to the CUDA image.
As for now, the docker image works despite this notification, so you can ignore it, and proceed with training/testing the framework using the provided scripts.

**Comment by Chaitanya887** [comment]
@matanr 
ran in my linux machine and it worked like a charm ❤

Final Question 
Can we somehow get the list of coordinates(x, y) for every keypoint that are being generated, that are positioned in the query image along with numbers ?
![image](https://github.com/matanr/capex/assets/99232731/e7aab50a-d05a-4d85-87f6-30de672268ba)
