### ISSUE TITLE
About Support Text-Graph Used in Figure 6

### ISSUE THREAD

**Issue by yzrs** [matanr/capex#5]
@matanr Thanks for your valuable contributions.

Regarding Figure 6 in the paper, it is evident that CapeX performs exceptionally well across various levels of text and pose-graph abstractions. However, the input details are somewhat unclear. I am curious whether the text and pose-graphs utilized here are based on the entire body skeleton or just a segment of it. Could you provide some additional insights?
![image](https://github.com/user-attachments/assets/30db513c-8e00-4d58-83a8-35840b41d897)
Furthermore, if the visualization script could also be provided, it would be greatly appreciated.

Best regards,

**Comment by matanr** [comment]
Thank you for your interest and positive feedback!

In each of the six examples, the input skeleton is drawn directly onto the output image. For instance:

- In the leftmost horse image, the provided text-graph consists of a single node: animal (node 0) with no edges.

- In the middle horse image, the provided text-graph is a graph with 7 nodes. The edges are visible in the image; for example, the head (node 0) is connected to the body (node 1).

I hope this explanation clarifies things.

Regarding the visualization script, have you tried using ``demo_text.py``?

**Comment by yzrs** [comment]
I think my question has been addressed. 

Regarding the visualization script, I will look into using demo_text.py as you suggested. 

Thank you very much for your detailed explanation and for taking the time to clarify my doubts.

Best regards,
